apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: my-tlakomer-cert
spec:
  domains:
    - tlakomer.com
    - www.tlakomer.com
    - my.tlakomer.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tlakomer-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ingress-externalip
    networking.gke.io/managed-certificates: my-tlakomer-cert
    ingress.gcp.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: tlakomer.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: tlakomer-be-svc
            port:
              number: 8088
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: tlakomer-be-svc
            port:
              number: 8088
      - path: /v3/api-docs
        pathType: Prefix
        backend:
          service:
            name: tlakomer-be-svc
            port:
              number: 8088
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tlakomer-fe-svc
            port:
              number: 80